version: "3.3"
services:
  telegram_bot_app:
    container_name: volleybot
    build:
      context: .
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./volleybot/data:/app/data
    restart: always
