from os import environ

TELEGRAM_BOT_TOKEN = environ['TELEGRAM_BOT_TOKEN']
ACCESS_WHITE_LIST = environ['ACCESS_WHITE_LIST'].split(',') if 'ACCESS_WHITE_LIST' in environ else None
DEV_CHAT_ID = int(environ['DEV_CHAT_ID'])
CACHE_FILE_PATH = environ['CACHE_FILE_PATH']

DEFAULT_SPR_ID = environ['DEFAULT_EXPORT_SPR_ID']
TEAMS_TEMPLATE_ID = environ['TEAMS_SPR_TEMPLATE_ID']
TOURNAMENT_TEMPLATE_ID = environ['TOURNAMENT_SPR_TEMPLATE_ID']

GRANT_SPR_PERMISSION = environ['GRANT_SPR_PERMISSION'].split(',') if 'GRANT_SPR_PERMISSION' in environ else []
